name: Excel test

on:
  schedule:
    # Run every day at 00:05 UTC
    - cron: '5 0 * * *'
    - cron: '5 9 * * *'
    - cron: '5 11 * * *'  
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update-reports:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install requests
      run: pip install requests
      
    - name: Install openpyxl
      run: pip install openpyxl

    - name: Install XlsxWriter
      run: pip install XlsxWriter

    - name: Install lxml
      run: pip install lxml
        
    - name: Run script
      run: python reportMonitor.py
      
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add parliament_data.xlsx
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update reports - $(date +'%Y-%m-%d %H:%M')" && git push)
